---
- name: Reload sshd Debian
  listen: Reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Reload sshd RedHat
  listen: Reload sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded
  when: ansible_distribution == "Amazon" or ansible_distribution == "RedHat"
